version: "14.0.0"

check:
  physics:

    thresholds:
      50: "intave internals sendnotify &c{player}&7/{trust-color}&7 is moving incorrectly"
      100:
        - "intave internals sendnotify &c{player}&7/{trust-color}&7 has been removed for moving incorrectly"
        - "kick {player} &cYou have been removed from the game based on data that was collected by the anti-cheat"

  timer:

    thresholds:
      50: "intave internals sendnotify &c{player}&7/{trust-color}&7 is moving too frequently / is lagging"
      100:
        - "intave internals sendnotify &c{player}&7/{trust-color}&7 is moving too frequently / is lagging for a long period"

  heuristics:

    enabled: true

    disable-reducing: true

    confidence-thresholds:
      "!!":
        25:
          - "intave internals sendnotify &c{player}&7/{trust-color}&7 has been removed for attacking suspiciously (!!) (heuristics)"
          - "kick {player} &cYou have been removed from the game based on data that was collected by the anti-cheat"

      "!":
        25: "intave internals sendnotify &c{player}&7/{trust-color}&7 is attacking suspiciously (!) (heuristics)"
        50:
          - "intave internals sendnotify &c{player}&7/{trust-color}&7 has been removed for attacking suspiciously (!) (heuristics)"
          - "kick {player} &cYou have been removed from the game based on data that was collected by the anti-cheat"

      "?!":
        50: "intave internals sendnotify &c{player}&7/{trust-color}&7 is attacking suspiciously (?!) (heuristics)"
        75: "intave internals sendnotify &c{player}&7/{trust-color}&7 is attacking suspiciously #2 (?!) (heuristics)"

  attackraytrace:

    enabled: true

    thresholds:
      50: "intave internals sendnotify &c{player}&7/{trust-color}&7 is attacking suspiciously (hitbox)"
      100:
        - "intave internals sendnotify &c{player}&7/{trust-color}&7 has been removed for attacking suspiciously (hitbox)"
        - "kick {player} &cYou have been removed from the game based on data that was collected by the anti-cheat"

  interactionraytrace:

    enabled: true

    thresholds:
      50: "intave internals sendnotify &c{player}&7/{trust-color}&7 is interacting suspiciously"
      100:
        - "intave internals sendnotify &c{player}&7/{trust-color}&7 is interacting suspiciously #2"

  protocolscanner:

    enabled: true

    invokant: false

    thresholds:
      50: "intave internals sendnotify &c{player}&7/{trust-color}&7 is sending invalid packets"
      100:
        - "intave internals sendnotify &c{player}&7/{trust-color}&7 has been removed for moving incorrectly"
        - "kick {player} &cYou have been removed from the game based on data that was collected by the anti-cheat"

  placementanalysis:

    enabled: true

    thresholds:
      50: "intave internals sendnotify &c{player}&7/{trust-color}&7 is placing blocks incorrectly"
      100:
        - "intave internals sendnotify &c{player}&7/{trust-color}&7 has been removed for placing blocks incorrectly"
        - "kick {player} &cYou have been removed from the game based on data that was collected by the anti-cheat"

  inventoryclickanalysis:

    enabled: true

    thresholds:
      50: "intave internals sendnotify &c{player}&7/{trust-color}&7 is clicking suspiciously on items"
      100:
        - "intave internals sendnotify &c{player}&7/{trust-color}&7 has been removed for clicking suspiciously on items"
        - "kick {player} &cYou have been removed from the game based on data that was collected by the anti-cheat"

  clickspeedlimiter:

    enabled: true

    max-cps: 20

    thresholds:
      50: "intave internals sendnotify &c{player}&7/{trust-color}&7 is attacking too quickly"
      100:
        - "intave internals sendnotify &c{player}&7/{trust-color}&7 has been removed for attacking too quickly"
        - "kick {player} &cYou have been removed from the game based on data that was collected by the anti-cheat"

  abilityspeedlimiter:

    # pure emptiness

blacklist:

  apply: true

proxy:

  enable: false

filter:

  health: true

  enchantments: true

  chat-insults: true

  chat-spam: true

command:

  hide: true

rejoin:

  delay: 3600

  message: "&cYou were recently removed, please wait before connecting again"

logging:

  console_log: false

  file_log: true

layout:

  verbose: "{prefix} &c{player}&7/{trust-color}&7 {message} {details} (+{vladded} -> {vl})"

  notify: "{prefix} &c&lNotify&8: &7{text}"

  prefix: "&8[&c&lIntave&8]&7 "