check:
  physics:


  heuristics:


  attackRaytrace:


  interactionRaytrace:


  abilitySpeedLimiter:


  protocolScanner:


  chat:


layout:

  verbose: "{prefix} &c{player}&7/{trust-color}&7 {message} {details} (+{vladded} -> {vl})"

  notify: "{prefix} &cWARNING&7: &c{player}&7/{trust-color}&7 {text}"

  prefix: "&8[&c&lIntave&8]&7 "

filter:

  health: true

  enchantments: true

