name: Intave
authors: [DarkAndBlue, vento, Jpx3]
version: @VERSION@
api-version: 1.13
description: @DESCRIPTION@

main: de.jpx3.intave.IntavePlugin
database: false
softdepend: [ProtocolLib, ViaVersion]

commands:
  intave:
    aliases:
      - iac

default-permission: false

permissions:
  intave.bypass:
    default: false

  intave.trust.green:
    default: op

  intave.trust.yellow:
    default: false

  intave.trust.orange:
    default: false

  intave.trust.red:
    default: false

  intave.trust.darkred:
    default: false

  intave.command:
    default: op

  intave.command.notify:
    default: op

  intave.command.verbose:
    default: op

  intave.command.restart:
    default: op

  intave.command.internals.*:
    default: false

    children:
      intave.command.internals.delay: true
      intave.command.internals.rejoinblock: true
      intave.command.internals.sendnotify: true

  intave.command.internals.delay:
    default: false

  intave.command.internals.rejoinblock:
    default: false

  intave.command.internals.sendnotify:
    default: false