name: Intave
authors: [Jpx3, ventolotl, DarkAndBlue]
version: @VERSION@
api-version: 1.13
description: @DESCRIPTION@

main: de.jpx3.intave.IntavePlugin
database: false
softdepend: [ProtocolLib, ViaVersion]

commands:
  intave:
    aliases:
      - iac

default-permission: false

permissions:
  intave.bypass:
    default: false

  intave.trust.darkgreen:
    default: false

  intave.trust.green:
    default: false

  intave.trust.yellow:
    default: false

  intave.trust.orange:
    default: false

  intave.trust.red:
    default: false

  intave.trust.darkred:
    default: false

  intave.command.notify:
    default: op

  intave.command.verbose:
    default: op