version: "14.0.0"
state: 0

check:
  physics:
    high-tolerance: false

    # Mitigation mode
    # Choose between AGGRESSIVE, CAREFUL, LENIENT and SILENT
    # Trustfactor mappings and high-tolerance modes are supported throughout all of them
    mitigation: CAREFUL

    # Experimental feature, reduces feedback-related false positives
    use-superpositions: false

    # Unused, will be removed in the future
    speculative-forward-emulation:
      enabled: false
      activation-threshold: 0
      ticks: 3
      ticks-for-hard-sync: -1

    on-detection:
      reset-item-usage: true
      close-inventory: true
      refresh-nearby-blocks: true

    thresholds:
      100: "intave internals sendnotify &c{player}&7/{trust-color}&7 is moving incorrectly"
      400: "intave internals sendnotify &c{player}&7/{trust-color}&7 is moving incorrectly #2"
      500: "intave internals storelog {player} {check} {vl}"
      999:
        - "intave internals kickip {player} &cYou have been kicked, as an account with your ip address was removed from the game"
        - "kick {player} &cYou have been removed from the game based on data that was collected by the anti-cheat"

  timer:
    high-tolerance: true
    reverse-blink: true
    reverse-lag: false
    low-tolerance: false
    reduce-stutter-hits: false

    thresholds:
      50: "intave internals sendnotify &c{player}&7/{trust-color}&7 is moving too frequently / is lagging"
      100: "intave internals sendnotify &c{player}&7/{trust-color}&7 is moving too frequently / is lagging for a long period"

  heuristics:
    enabled: true
    combat-sampling: true
    disable-reducing: false
    confidence-thresholds:
      "!!":
        25:
          - "intave internals storelog {player} {check} {vl}"
          - "intave internals sendnotify &c{player}&7/{trust-color}&7 has been removed for attacking suspiciously (!!) (heuristics)"
          - "intave internals kickip {player} &cYou have been kicked, as an account with your ip address was removed from the game"
          - "kick {player} &cYou have been removed from the game based on data that was collected by the anti-cheat"
      "!":
        25:
          - "intave internals storelog {player} {check} {vl}"
          - "intave internals sendnotify &c{player}&7/{trust-color}&7 is attacking suspiciously (!) (heuristics)"
        50:
          - "intave internals sendnotify &c{player}&7/{trust-color}&7 has been removed for attacking suspiciously (!) (heuristics)"
          - "intave internals kickip {player} &cYou have been kicked, as an account with your ip address was removed from the game"
          - "kick {player} &cYou have been removed from the game based on data that was collected by the anti-cheat"
      "?!":
        50: "intave internals sendnotify &c{player}&7/{trust-color}&7 is attacking suspiciously (?!) (heuristics)"
        75: "intave internals sendnotify &c{player}&7/{trust-color}&7 is attacking suspiciously #2 (?!) (heuristics)"

  attackraytrace:
    enabled: true
    applicable-thresholds:
      reach:
        50: "intave internals sendnotify &c{player}&7/{trust-color}&7 is attacking suspiciously (reach)"
        100:
          - "intave internals storelog {player} {check} {vl}"
          - "intave internals sendnotify &c{player}&7/{trust-color}&7 has been removed for attacking suspiciously (reach)"
          - "intave internals kickip {player} &cYou have been kicked, as an account with your ip address was removed from the game"
          - "kick {player} &cYou have been removed from the game based on data that was collected by the anti-cheat"

      hitbox:
        50: "intave internals sendnotify &c{player}&7/{trust-color}&7 is attacking suspiciously (hitbox)"
        100: "intave internals sendnotify &c{player}&7/{trust-color}&7 is attacking suspiciously #2 (hitbox)"

  interactionraytrace:
    enabled: true
    thresholds:
      50: "intave internals sendnotify &c{player}&7/{trust-color}&7 is interacting suspiciously"
      100: "intave internals sendnotify &c{player}&7/{trust-color}&7 is interacting suspiciously #2"

  clickpatterns:
    enabled: true
    thresholds:
      50: "intave internals sendnotify &c{player}&7/{trust-color}&7 is clicking statistically anomalously (auto-clicker)"
      100:
        - "intave internals sendnotify &c{player}&7/{trust-color}&7 has been removed for clicking statistically anomalously (auto-clicker)"
        - "intave internals kickip {player} &cYou have been kicked, as an account with your ip address was removed from the game"
        - "kick {player} &cYou have been removed from the game based on data that was collected by the anti-cheat"

  clickspeedlimiter:
    enabled: true
    max-cps: 20
    thresholds:
      50: "intave internals sendnotify &c{player}&7/{trust-color}&7 is attacking too quickly"
      100:
        - "intave internals sendnotify &c{player}&7/{trust-color}&7 has been removed for attacking too quickly"
        - "intave internals kickip {player} &cYou have been kicked, as an account with your ip address was removed from the game"
        - "kick {player} &cYou have been removed from the game based on data that was collected by the anti-cheat"

  breakspeedlimiter:
    enabled: true
    thresholds:
      100: "intave internals sendnotify &c{player}&7/{trust-color}&7 is breaking blocks too quickly"

  protocolscanner:
    enabled: true
    invokant: false
    check_sent_slot_twice_vl: 100
    thresholds:
      50: "intave internals sendnotify &c{player}&7/{trust-color}&7 is sending invalid packets"
      100:
        - "intave internals sendnotify &c{player}&7/{trust-color}&7 has been removed for sending invalid packets"
        - "intave internals kickip {player} &cYou have been kicked, as an account with your ip address was removed from the game"
        - "kick {player} &cYou have been removed from the game based on data that was collected by the anti-cheat"

  placementanalysis:
    enabled: true
    check_timings: false
    thresholds:
      50: "intave internals sendnotify &c{player}&7/{trust-color}&7 is placing blocks incorrectly"
      100:
        - "intave internals storelog {player} {check} {vl}"
        - "intave internals sendnotify &c{player}&7/{trust-color}&7 has been removed for placing blocks incorrectly"
        - "intave internals kickip {player} &cYou have been kicked, as an account with your ip address was removed from the game"
        - "kick {player} &cYou have been removed from the game based on data that was collected by the anti-cheat"

  inventoryclickanalysis:
    enabled: true
    high-tolerance: true
    thresholds:
      50: "intave internals sendnotify &c{player}&7/{trust-color}&7 is performing invalid item-operations"
      100:
        - "intave internals sendnotify &c{player}&7/{trust-color}&7 has been removed for clicking suspiciously on items"
        - "intave internals kickip {player} &cYou have been kicked, as an account with your ip address was removed from the game"
        - "kick {player} &cYou have been removed from the game based on data that was collected by the anti-cheat"

storage:
  # Set to ignore the "storelog" command and auto-store suggested violations instead?
  auto-logs: false

  # Set to let Intave find a suitable trustfactor when you don't specify one
  auto-trustfactor: true

blacklist:
  apply: true
  message-in-chat: false
  message: "&cYou are on an anti-cheat blacklist and can't join this server"

proxy:
  enable: false

clientwarning:
  enable: true

# Only works when intave-storage is used
accountcheck:
  enable: true

  only-red-trustfactor: true
  # LOWER_TRUSTFACTOR, LOWEST_TRUSTFACTOR, KICK
  action: KICK

  kick-message-in-chat: true
  kick-message: "&cDue to high abuse, your account needs to be at least a month old to join this server."

filter:
  health: false
  vanish: true
  equipmentdata: false

command:
  hide: true
  reroute:
    "/alerts": "/intave verbose"
    "/cps": "/intave cps"

rejoin:
  # Don't forget to reset this value when you deactivate it
  delay: 3600
  refresh: true
  message: "&cYou were removed recently, wait before connecting again"

# You should disable any of these options **ONLY**
# when experiencing serious problems and **ONLY** after reporting the issue to us.
# Leaving any of these disabled can result to severely reduced security and stability.
fault-kicks:
  position-faults: true
  missing-position-update: true
  feedback-faults: true
  ignoring-feedback: true
  ignoring-keep-alive: true
  invalid-key-input: true
  invalid-player-action: true

logging:
  console-log: false
  file-log: true

analytics:
  errorReporting: true
  usageReporting: true

layout:
  verbose: "{prefix} &c{player}&7/{trust-color}&7 {message} {details} (+{vladded} -> {vl})"
  notify: "{prefix} &c&lNotify&8: &7{text}"
  prefix: "&8[&c&lIntave&8]&7 "