version: "14.0.0"
state: 0

check:
  physics:

    thresholds:
      50: "intave internals sendnotify &c{player}&7/{trust-color}&7 is moving incorrectly"
      100:
        - "intave internals sendnotify &c{player}&7/{trust-color}&7 is moving incorrectly #2"
      999:
        - "intave internals collectivekick {player} &cYou have been kicked, because an account with your ip address was removed from the game"
        - "kick {player} &cYou have been removed from the game based on data that was collected by the anti-cheat"

  timer:

    high-tolerance: false

    thresholds:
      50: "intave internals sendnotify &c{player}&7/{trust-color}&7 is moving too frequently / is lagging"
      100:
        - "intave internals sendnotify &c{player}&7/{trust-color}&7 is moving too frequently / is lagging for a long period"

  heuristics:

    enabled: true

    disable-reducing: false

    confidence-thresholds:
      "!!":
        25:
          - "intave internals sendnotify &c{player}&7/{trust-color}&7 has been removed for attacking suspiciously (!!) (heuristics)"
          - "intave internals collectivekick {player} &cYou have been kicked, because an account with your ip address was removed from the game"
          - "kick {player} &cYou have been removed from the game based on data that was collected by the anti-cheat"

      "!":
        25: "intave internals sendnotify &c{player}&7/{trust-color}&7 is attacking suspiciously (!) (heuristics)"
        50:
          - "intave internals sendnotify &c{player}&7/{trust-color}&7 has been removed for attacking suspiciously (!) (heuristics)"
          - "intave internals collectivekick {player} &cYou have been kicked, because an account with your ip address was removed from the game"
          - "kick {player} &cYou have been removed from the game based on data that was collected by the anti-cheat"

      "?!":
        50: "intave internals sendnotify &c{player}&7/{trust-color}&7 is attacking suspiciously (?!) (heuristics)"
        75: "intave internals sendnotify &c{player}&7/{trust-color}&7 is attacking suspiciously #2 (?!) (heuristics)"

  attackraytrace:

    enabled: true

    uncertainty-vl: false

    apply-hitbox-vl: true

    applicable-thresholds:
      reach:
        50: "intave internals sendnotify &c{player}&7/{trust-color}&7 is attacking suspiciously (reach)"
        100:
          - "intave internals sendnotify &c{player}&7/{trust-color}&7 has been removed for attacking suspiciously (reach)"
          - "intave internals collectivekick {player} &cYou have been kicked, because an account with your ip address was removed from the game"
          - "kick {player} &cYou have been removed from the game based on data that was collected by the anti-cheat"

      hitbox:
        50: "intave internals sendnotify &c{player}&7/{trust-color}&7 is attacking suspiciously (hitbox)"
        100: "intave internals sendnotify &c{player}&7/{trust-color}&7 is attacking suspiciously #2 (hitbox)"

  interactionraytrace:

    enabled: true

    thresholds:
      50: "intave internals sendnotify &c{player}&7/{trust-color}&7 is interacting suspiciously"
      100:
        - "intave internals sendnotify &c{player}&7/{trust-color}&7 is interacting suspiciously #2"

  breakspeedlimiter:

    enabled: true

    thresholds:
      100: "intave internals sendnotify &c{player}&7/{trust-color}&7 is breaking blocks too quickly"

  protocolscanner:

    enabled: true

    invokant: false

    thresholds:
      50: "intave internals sendnotify &c{player}&7/{trust-color}&7 is sending invalid packets"
      100:
        - "intave internals sendnotify &c{player}&7/{trust-color}&7 has been removed for sending invalid packets"
        - "intave internals collectivekick {player} &cYou have been kicked, because an account with your ip address was removed from the game"
        - "kick {player} &cYou have been removed from the game based on data that was collected by the anti-cheat"

  placementanalysis:

    enabled: true

    thresholds:
      50: "intave internals sendnotify &c{player}&7/{trust-color}&7 is placing blocks incorrectly"
      100:
        - "intave internals sendnotify &c{player}&7/{trust-color}&7 has been removed for placing blocks incorrectly"
        - "intave internals collectivekick {player} &cYou have been kicked, because an account with your ip address was removed from the game"
        - "kick {player} &cYou have been removed from the game based on data that was collected by the anti-cheat"

  inventoryclickanalysis:

    enabled: true

    thresholds:
      50: "intave internals sendnotify &c{player}&7/{trust-color}&7 is performing invalid item-operations"
      100:
        - "intave internals sendnotify &c{player}&7/{trust-color}&7 has been removed for clicking suspiciously on items"
        - "intave internals collectivekick {player} &cYou have been kicked, because an account with your ip address was removed from the game"
        - "kick {player} &cYou have been removed from the game based on data that was collected by the anti-cheat"

  clickspeedlimiter:

    enabled: true

    max-cps: 20

    thresholds:
      50: "intave internals sendnotify &c{player}&7/{trust-color}&7 is attacking too quickly"
      100:
        - "intave internals sendnotify &c{player}&7/{trust-color}&7 has been removed for attacking too quickly"
        - "intave internals collectivekick {player} &cYou have been kicked, because an account with your ip address was removed from the game"
        - "kick {player} &cYou have been removed from the game based on data that was collected by the anti-cheat"

  abilityspeedlimiter:

    # pure emptiness

blacklist:

  apply: true

proxy:

  enable: false

clientwarning:

  enable: true

filter:

  health: true

  equipmentdata: true

  chat-insults: true

  chat-spam: true

command:

  hide: true

rejoin:

  delay: 3600

  refresh: true

  message: "&cYou were recently removed, please wait before connecting again"

logging:

  console-log: false

  file-log: true

layout:

  verbose: "{prefix} &c{player}&7/{trust-color}&7 {message} {details} (+{vladded} -> {vl})"

  notify: "{prefix} &c&lNotify&8: &7{text}"

  prefix: "&8[&c&lIntave&8]&7 "