# Selected configuration
# Enter "file" to use a file configuration (settings.yml)
# Or enter the name of your online configuration to use an online configuration
config-identifier: "file"

# Selected server mapping file in custom format
# Enter "online" for the online mapping file
# Enter a file name - "myserver.ilm" for example - to use a custom mapping file.
server-mappings: "online"

# Selected server mapping file in custom format
# Enter "online" for the online mapping file
# Enter a file name - "myserver.tfm" for example - to use a custom mapping file.
trustfactor-mappings: "online"


