package de.jpx3.intave.module.violation;

import de.jpx3.intave.IntaveLogger;
import de.jpx3.intave.IntavePlugin;
import de.jpx3.intave.module.violation.placeholder.PlaceholderContext;
import de.jpx3.intave.module.violation.placeholder.Placeholders;
import de.jpx3.intave.module.violation.placeholder.TextContext;
import de.jpx3.intave.module.violation.placeholder.ViolationPlaceholderContext;
import de.jpx3.intave.user.User;
import de.jpx3.intave.user.UserRepository;
import org.bukkit.ChatColor;
import org.bukkit.entity.Player;

public final class MessageFormatter {
  public static String resolveVerboseMessage(
    Player player, PlaceholderContext placeholderContext, ViolationOutputMode violationOutputMode
  ) {
    String messageLayout = resolveLayout(violationOutputMode.layoutPath());
    User user = UserRepository.userOf(player);
    String output = Placeholders.replacePlaceholders(
      messageLayout,
      Placeholders.PLUGIN_CONTEXT,
      Placeholders.SERVER_CONTEXT,
      user.userContext(),
      user.playerContext(),
      placeholderContext
    );
    output = ChatColor.translateAlternateColorCodes('&', output);
    output = output.trim().replace("  ", " ");
    return output;
  }

  public static String resolveNotifyReplacements(TextContext textContext) {
    String messageLayout = resolveLayout("notify");
    String output = Placeholders.replacePlaceholders(
      messageLayout,
      Placeholders.PLUGIN_CONTEXT,
      Placeholders.SERVER_CONTEXT,
      textContext
    );
    output = ChatColor.translateAlternateColorCodes('&', output);
    output = output.trim().replace("  ", " ");
    return output;
  }

  public static String resolveCommandReplacements(Player player, String command, ViolationPlaceholderContext violationPlaceholderContext) {
    User user = UserRepository.userOf(player);
    String output = Placeholders.replacePlaceholders(
      command,
      Placeholders.PLUGIN_CONTEXT,
      Placeholders.SERVER_CONTEXT,
      user.userContext(),
      user.playerContext(),
      violationPlaceholderContext
    );
    output = ChatColor.translateAlternateColorCodes('&', output);
    output = output.trim().replace("  ", " ");
    return output;
  }

  // Mirrors the defaults in advanced.yml. If the layout key is missing from the
  // resolved configuration (e.g. an advanced.yml generated by an older version),
  // getString returns null and every verbose/notify message silently collapses
  // to an empty line — fall back to the shipped default instead.
  private static final String DEFAULT_VERBOSE_LAYOUT =
    "{prefix} &c{player}&7/{trust-color}&7 {message} {details} (+{vladded} -> {vl})";
  private static final String DEFAULT_NOTIFY_LAYOUT =
    "{prefix} &c&lNotify&8: &7{text}";

  private static boolean warnedMissingLayout;

  private static String resolveLayout(String key) {
    String layout = IntavePlugin.singletonInstance().settings().getString("layout." + key);
    if (layout == null || layout.isEmpty()) {
      if (!warnedMissingLayout) {
        warnedMissingLayout = true;
        IntaveLogger.logger().warn("Missing 'layout." + key + "' in configuration, using built-in default"
          + " (your advanced.yml may predate this setting)");
      }
      return "notify".equals(key) ? DEFAULT_NOTIFY_LAYOUT : DEFAULT_VERBOSE_LAYOUT;
    }
    return layout;
  }
}
